import type { Metadata } from "next";
// font is loaded via CSS in globals.css
import "./globals.css";
import { CanvasTokenProvider } from "./components/CanvasTokenProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <CanvasTokenProvider>{children}</CanvasTokenProvider>
      </body>
    </html>
  );
}



